### ISSUE TITLE
Updates not working ? 

### ISSUE THREAD

**Issue by Zack7292** [jobobby04/TachiyomiSY#1011]
### Steps to reproduce

1. Try to update a categorie or your entire library
2.  see that it doesn't do it

### Expected behavior

I'm expecting it to update my entries, and since ik that some had new chapters released i expecte them all to momentarily pop up following the notification that shows the progress of the update of my library.

### Actual behavior

Since this moring (i have upgraded to 1.10.1) i seem to be unable to properly do any update for any of my manga, whne i do it, all it does is start the notification and after immidiately disapear and then doesn't actually do the update of my library, it seem to work at times when i o it on individual series tho (not every times, i sometime need to try 2-3 times before it works) b4 i updated, it seemed to be updating properly.

its almost as if its trying to do the update and then immidiately stops doing it

### Tachiyomi version

SY's  1.10.1

### Android version

Android 13

### Device

Samsung Galazy A71

### Other details

I have tried to restart my device and it kept occuring. I have series from MANY sources (mangasee, asurascan,reaper scan, immortal updates, manganato, ...) so maybe that could be a cause? idon't think so, but mentionning it could help ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
**Smart updates**
**Tachiyomi** intelligently works to reduce the number of series in a global update to reduce the load on sources. To be updated, a series has to meet the following conditions:
1. The series has been **started**, you've read at least one chapter.
2. The series is **not marked Completed** by the source, there's an expectation of more chapters in the future.
3. The series has **no unread chapters**, you've read all the chapters you already have,
4. There's been enough time since the last update for the series that **the app predicts a new chapter is available**. You can see how often the app predicts a new chapter for a series by looking at the hourglass. After that many days, the app will alow that series to check for updates.
