### ISSUE TITLE
Cannot add MAL or Anilist as Trackers

### ISSUE THREAD

**Issue by zlehnherr1** [jobobby04/TachiyomiSY#1279]
### Steps to reproduce

Go to settings ans trackers.
Click the icon for anilist or mal.
Login to account.
Tap allow to allow the connection. 
Either bounces back to app or sits there and spins.

### Expected behavior

After logging in and allowing the connection, I should be able to start tracking.

### Actual behavior

I cannot track with mal or anilist.

### TachiyomiSY version

1.10.5

### Android version

14

### Device

S22 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

* For MAL to work, you need to change the app's user-agent (SY Settings > Advanced > Default user-agent string) to something else. Afterwards, restart the app & try relinking again.
* For AniList, you will need to update your SY Stable into the SY Preview version for AniList to link properly. Otherwise, wait for a future SY Stable update containing the fix to AniList.

For any future questions about this, or other minor questions/issues, come to the Mihon Discord #tachiyomi-sy channel for help.

**Comment by zlehnherr1** [comment]
> > I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.
> 
> Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.
> 
> * For MAL to work, you need to change the app's user-agent (SY Settings > Advanced > Default user-agent string) to something else. Afterwards, restart the app & try relinking again.
> * For AniList, you will need to update your SY Stable into the SY Preview version for AniList to link properly. Otherwise, wait for a future SY Stable update containing the fix to AniList.
> 
> For any future questions about this, or other minor questions/issues, come to the Mihon Discord #tachiyomi-sy channel for help.

I must have somehow gotten over to the mihon github instead of SY. Thanks for the info.
