### ISSUE TITLE
[Bug] <Mangadex Login Error>

### ISSUE THREAD

**Issue by Xhandrt** [jobobby04/TachiyomiSY#240]
## Device information
* Tachiyomi version:  Stable 1.5.0
* Android version:  Android 8.1.0
* Device: Redmi Note 5

## Steps to reproduce
1. Mangadex settings
2. Mangadex login
3. Enter login details

### Expected behavior
Should log me in

### Actual behavior
Displaying Unknown error

## Other details
1. Recommendations not working since not logging me in.
2.  Login details are correct and verified.
3.  Tried with and without 2FA for same result.(Screenshot)↓
4. Checked on internet and happening with other fork namely "neko".(Screenshot)↓
Attachments.
![Screenshot_2021-03-12-16-05-24-811_com android chrome](https://user-images.githubusercontent.com/80518280/110928891-61b67500-834d-11eb-84d7-ecdd0747033d.jpg)

![Screenshot_2021-03-12-15-04-16-887_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/80518280/110928773-421f4c80-834d-11eb-9b5a-a5266983e5f9.jpg)

**Comment by ExAnchoR** [comment]
It also happens to me whenever I log in on the app. also it seems that it only log in you to the webview because when I tried to log in to the webview of the app it's already logged in, so just to make sure I log out it (in the webview) and log in it again in the app and I open the webview my account is already logged in.
![Uploading Screenshot_20210313-094504.png…]()
![Uploading Screenshot_20210313-094536.png…]()
![Uploading Screenshot_20210313-094547.png…]()

**Comment by jobobby04** [comment]
It's fixed for the next release, download the preview build(link in the readme) for now

**Comment by ExAnchoR** [comment]
Okay, thank you so much sir!
wish you a good health and luck
