### ISSUE TITLE
how do i provide a translation specifically for this fork features

### ISSUE THREAD

**Issue by adsewse2015** [jobobby04/TachiyomiSY#407]

**Comment by adsewse2015** [comment]
its TH by the way

**Comment by jobobby04** [comment]
Hey! You can download the xml file located [here(right click - save page as - if it doesn't immediately download)](https://raw.githubusercontent.com/jobobby04/TachiyomiSY/master/app/src/main/res/values/strings_sy.xml) and send it to me or upload it to this issue here, I will close this but keep watch on any future updates you provide
