### ISSUE TITLE
[Bug] nhentai downloaded badge not showing 

### ISSUE THREAD

**Issue by yooman1213** [jobobby04/TachiyomiSY#54]
After downloading a chapter from nhentai and the force closing app from task manager (swiping from navigation button) the green downloaded badge is missing after loading the library, and it only happen to nhentai downloaded doujin / manga, but it can be open without connection, and the doujin/manga cant be deleted from app

---
 Device information =
* Tachiyomi version: version 150
* Android version: 9
* Device: samsung s8+

 Steps to reproduce =
1. First step
Download any doujin on nhentai 
2. Second step
After downloading it force close aplication ( swiping from navigation button)
3. Third step 
Open the app again let it load the library, then the green downloaded badge is missing 

Expected behavior
The green downloaded badge not missing

 Actual behavior
The green downloaded badge is missing

**Comment by scb261** [comment]
The bug is also present for exhentai and probably other internal sources. I did some debugging, but my knowledge isn't enough to resolve this. Maybe it will help someone else or maybe someone could give me a hint, so I'm posting here what I got.

https://github.com/jobobby04/TachiyomiSY/blob/a8f2f0356242bf259ab12fffd37c27cac6c4fb2b/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadCache.kt#L124-L132

Set breakpoint on line 125 or 127 (result will be different depending on the line). Now open the app with connected debugger (you need to catch it when app is opening). 

When you set breakpoint on line 125 and Step Over (F8) once, look at the size of `onlineSources`. Remember this number (in my case it's 133). You can also copy `onlineSources`' elements into notepad to compare them with the next result. Continue executing, the bug will be absent.

When you set breakpoint on line 127, you'll see that size of `onlineSources` is 6 less then previous case (in my case it's 126). If you compare its elements to previous result, you'll see that internal sources (like nhentai and e-hentai) are absent and therefore corresponding folders will be filtered out on lines 130-132. The bug will be present.

Some other details:
- It was tested with a8f2f03
- It was tested on physical phone since my PC doesn't have enough memory for emulator.
- I also tried some other breakpoints and at some point some other sources were absent (I think it also was 6, not sure) while internal ones were present, but I don't remember how exactly I set breakpoints then. Also I tried to modify code a little bit and that could be reason why some non-internal were absent. I'm not sure how it could cause it, though.

**Comment by jobobby04** [comment]
Thanks, that was exactly what I needed to fix it! I narrowed it down to the extension versions, when installed, will take control of the folder even though they should be blacklisted, so I did just that, blacklisted them 😄 
Here is the fix if you want to take a look at it https://github.com/jobobby04/TachiyomiSY/commit/ae48c1d7d4430f52979a734dcaad76cabdc90cff
This will be closed when the next release is out

**Comment by scb261** [comment]
Just pulled and tried out - the bug is still present. And I don't see how ae48c1d would fix it. The problem is that internal sources are missing from `onlineSources`, and ae48c1d added filter for some reason. The real problem somewhere in `sourceManager` since `sourceManager.getOnlineSources()` doesn't return full list. And when I'm trying to debug inside it, the bug for some reason disappears (at least in a8f2f03, didn't try the last one).

ae48c1d says that it fixes the bug when extension is also installed, but I don't have nhentai and exhentai extensions and bug is present. Well, I did have them installed before, maybe the app remembers it, idk.

**Comment by jobobby04** [comment]
I was just about to take a deeper look into it, I saw it still happening on my emulator 😄

**Comment by jobobby04** [comment]
Well dam, I have narrowed it down to the checkrenew running too early, before the source manager has time to register the internal sources

**Comment by jobobby04** [comment]
I found a good fix, the flow wasn't registering the sources fast enough, so I changed it to a immediate flow and it now works properly
Here is the fix if you want to take a look at it, the important part is the init edits in the SourceManager
