### ISSUE TITLE
Cannot create a backup

### ISSUE THREAD

**Issue by Sualem** [jobobby04/TachiyomiSY#599]
### Steps to reproduce

I try to backup the data on tachiyomiSY, and it creates a 0 byte file, and it keeps on "backuping".
I am unable to reach my library while the backup is in progress.
And it starts trying to backup again once I start the application.

### Expected behavior

It should backup the library.

### Actual behavior

App gets stuck at startup while it keeps on trying to backup every time I start the app

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/8660682/tachiyomi_crash_logs.txt)

### Tachiyomi version

Stable 1.8.3 (04/23/22 01:42)

### Android version

Android 11

### Device

Oppo CPH2211 Reno5 Z

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lucky777709** [comment]
I had this issue happen to me (twice) a few days ago, when an auto-backup started while I was in the middle of an EH Favorites sync.
The "Creating Backup" notification (at the top of my phone) persisted during the EH sync. After the sync ended, I noticed that after one auto-backup ended, it immediately started another auto-backup, and this was happening infinitely.
I tried clicking the manual backup option, but then it created a 0 byte file, because the infinite auto-backups didn't let the manual backup start correctly.

I had to reboot my phone, then the "Creating Backup" notification appeared not long after I rebooted, but this time the auto-backup finished correctly. If the backup still doesn't finish even after rebooting the phone, you may try doing a manual backup again via the app (that seemed to help somewhat).

By the way, in my case, the auto-backup feature works correctly if it starts and I'm not in the middle of an EH sync.

**Comment by lucky777709** [comment]
Today, I had the endless auto-backup issue happen again, but this time, it wasn't in the middle of an EH favorites sync.
As described above, I had to reboot my phone, then the auto-backup started again and eventually finished.

Tachiyomi version
Preview r455

Android version
Android 7.1.1

Device
Samsung Galaxy J2 Pro 2018 (SM-J250M)

**Comment by Sualem** [comment]
Hi,
Thanks for the information. I tried that, but it did not work.

**Comment by jobobby04** [comment]
This is probably fixed in the preview
