### ISSUE TITLE
Add custom extension list endpoint/url

### ISSUE THREAD

**Issue by dhupee** [jobobby04/TachiyomiSY#993]
### Describe your suggested feature

given the situation and with some users decided to fork and deal with the extensions him/herself is it possible to have a feature to link your tachiyomi to "custom url"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by noaione** [comment]
The feature is not working as intended since the following code will always throw an error: https://github.com/jobobby04/TachiyomiSY/blob/master/app/src/main/java/eu/kanade/tachiyomi/extension/api/ExtensionGithubApi.kt#L60-L64

`.awaitSuccess()`: https://github.com/jobobby04/TachiyomiSY/blob/master/core/src/main/java/eu/kanade/tachiyomi/network/OkHttpExtensions.kt#L115

**Comment by drewbitt** [comment]
Adding a custom repo to Browse > Edit Repos indeed does not populate a list of extensions as I expect.

**Comment by jobobby04** [comment]
It's fixed for the next build/release
